site_name: 旅游规划系统文档
repo_url: https://github.com/Yokumii/Data-Structure-Course-Design-Docs.git

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate

plugins:
  - search
  - redirects

nav:
  - 项目概述: index.md
  - 需求文档:
      - 功能需求: requirements/features.md
      - 数据规范: requirements/data.md
      - 用户用例: requirements/use_cases.md
  - 设计文档:
      - 系统架构: design/architecture.md
      - 算法设计: design/algorithm.md
  - API文档:
      - 后端接口: api/backend.md
      - 前端规范: api/frontend.md
  - 测试报告: test/cases.md
  - 部署指南: deployment/backend.md

extra:
  version: 1.0.0
  analytics:
    provider: google
    property: UA-XXXXX-Y

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences