site_name: 旅游规划系统文档
repo_url: https://github.com/Yokumii/Data-Structure-Course-Design-Docs.git

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate

plugins:
  - search
  - redirects

nav:
  - 项目概述: 
      - 项目介绍: home/index.md
      - 协作指南: home/guide.md
  - 提交材料:
      - 项目计划书: reports/plan.md
      - 第5周周报: reports/week5.md
      - 第6周周报: reports/week6.md
      - 第7周周报: reports/week7.md
      - 第8周周报: reports/week8.md
      - 第9周周报: reports/week9.md
      - 第10周周报: reports/week10.md
      - 第11周周报: reports/week11.md
      - 第12周周报: reports/week12.md
      - 第13周周报: reports/week13.md
      - 第14周周报: reports/week14.md
  - 需求文档:
      - 功能需求: requirements/features.md
      - 数据规范: requirements/data.md
      - 用户用例: requirements/use_cases.md
  - 设计文档:
      - 系统架构: design/architecture.md
      - 算法设计: design/algorithm.md
  - API文档:
      - 后端接口: api/backend.md
      - 前端规范: api/frontend.md
  - 测试报告: test/cases.md
  - 部署指南: deployment/backend.md

extra:
  version: 1.0.0
  analytics:
    provider: google
    property: UA-XXXXX-Y

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences